# Generated by Django 3.1 on 2022-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_user',
            name='current_user_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
